before_install:
  - wget http://www.veripool.org/ftp/verilator-3.886.tgz
  - export VERILATOR_ROOT=""
  - tar xzf verilator*.t*gz
  - cd verilator*
  - ./configure
  - make
  - sudo make install

language: cpp

script:
  - make lint


