sudo: required
dist: trusty
language: cpp

before_install:
  #- sudo apt-get install verilator
  #- git clone http://git.veripool.org/git/verilator
  #- cd verilator
  #- autoconf
  #- ./configure
  #- make
  #- sudo make install
  #- cd ..
   - git clone https://github.com/cornell-brg/verilator-travisci-cache.git
   - tar xfz verilator-travisci-cache/verilator-travis-3.876.tar.gz
   - export VERILATOR_ROOT=$PWD/verilator-3.876
   - export PATH=$VERILATOR_ROOT/bin:$PATH
  #- export PYMTL_VERILATOR_INCLUDE_DIR=$VERILATOR_ROOT/include
   - verilator --version

before_script:
  - make lint
  - make clean

script:
  - make regression

