sudo: required
dist: trusty
language: cpp

before_install:
  #- sudo apt-get install verilator
  - git clone http://git.veripool.org/git/verilator
  - cd verilator
  - autoconf
  - ./configure
  - make
  - sudo make install

before_script:
  - make lint
  - make clean

script:
  - make regression

