sudo: required
dist: trusty
language: cpp

before_install:
  #- sudo apt-get install verilator
  #- git clone http://git.veripool.org/git/verilator
  #- cd verilator
  #- autoconf
  #- ./configure
  #- make
  #- sudo make install
  #- cd ..
   - wget https://users.soe.ucsc.edu/~rafaeltp/files/verilator_3_888.tar.gz
   #- git clone https://github.com/cornell-brg/verilator-travisci-cache.git
   - tar xfz verilator-travisci-cache/verilator_3_888.tar.gz
   - export VERILATOR_ROOT=$PWD/verilator
   - export PATH=$VERILATOR_ROOT/bin:$PATH
   - verilator --version

before_script:
  - make lint
  - make clean

script:
  - make regression

